lexik_jwt_authentication:
    secret_key: "9hbu2f34u79h(*&Hf23f3"
    encoder:
        # token encoder/decoder service - default implementation based on the lcobucci/jwt library
        service:            lexik_jwt_authentication.encoder.lcobucci

        # encryption algorithm used by the encoder service
        signature_algorithm: HS256
